export class Interview {
    id!: string;
    empId!: number;
    employeeName!: string;
    email!: string;
    baselineDate!: Date;
    localGrade!: string;
    currentDayStatus!: string;
    mainProject!: string;
    accountName!: string;
    trainingBatchId!: string;
    mentorName!: string;
    trainingScoreFeedback!: string;
    bucket!: string;
    qualitativeFeedback!: string;
    oceanAttemptedTillDate!: string;
    oceanScoreIfAttempted!: number;
    hsCertificationDone!: string;
    digiDashboardUpdatedRegularly!: Date;
    accountShadowsDone!: string;
    currentStatus!: string;
    upskillingWhileOnBench!: string;
    currentInitiativeInvolvedIn!: string;
    workDoneLast3Months!: string;
    personReachable!: string;
    pscRemarks!: string;
    btoAverageQ3Attendance: any; // Replace with appropriate type
    sapienceAvgLast3Months!: number;
    leaveBalance!: number;
    leaveAppliedLast3Months!: number;
    botpStatus!: string;
    subStatus!: string;
    college!: string;
    collegeType!: string;
    education!: string;
    recruitmentSwarScore!: number;
    recruitmentAptitudeScore!: number;
    recruitmentCodingScore!: number;
}
